// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt_alJvyIPNiCNZQ0UBSlRILmZiI-e2cA',
    appId: '1:621083151558:web:f48e5e653ec39299461bc7',
    messagingSenderId: '621083151558',
    projectId: 'interest-db',
    authDomain: 'interest-db.firebaseapp.com',
    storageBucket: 'interest-db.firebasestorage.app',
    measurementId: 'G-E85415QCV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcVJ9EqIQlAY5Gi1eizGqrsaMNxI2Ix9A',
    appId: '1:621083151558:android:b2e1f41bef8a1ad9461bc7',
    messagingSenderId: '621083151558',
    projectId: 'interest-db',
    storageBucket: 'interest-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrp8vQE_j2WX5lzsA6hK-vwhAPnPcUJSo',
    appId: '1:621083151558:ios:6c99ce53cfb317b1461bc7',
    messagingSenderId: '621083151558',
    projectId: 'interest-db',
    storageBucket: 'interest-db.firebasestorage.app',
    iosBundleId: 'com.example.interest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrp8vQE_j2WX5lzsA6hK-vwhAPnPcUJSo',
    appId: '1:621083151558:ios:6c99ce53cfb317b1461bc7',
    messagingSenderId: '621083151558',
    projectId: 'interest-db',
    storageBucket: 'interest-db.firebasestorage.app',
    iosBundleId: 'com.example.interest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt_alJvyIPNiCNZQ0UBSlRILmZiI-e2cA',
    appId: '1:621083151558:web:edf2c807217fe5bc461bc7',
    messagingSenderId: '621083151558',
    projectId: 'interest-db',
    authDomain: 'interest-db.firebaseapp.com',
    storageBucket: 'interest-db.firebasestorage.app',
    measurementId: 'G-WQ4LGM99FM',
  );
}
